In [390]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [555]:
df = pd.read_csv('Lisboa por IQR2.csv')
df =df.drop(labels=["Unnamed: 0"], axis=1)
df

id           source  \
0                   208683      city scrape   
1                   211614  previous scrape   
2                   211616      city scrape   
3                   214729      city scrape   
4                   217281      city scrape   
...                    ...              ...   
24199  1243403799584587485      city scrape   
24200  1243421531996967673      city scrape   
24201  1243488183394801906      city scrape   
24202  1243509538559076353      city scrape   
24203  1243552535635447045      city scrape   

                                                    name  \
0                       Cozy central apartment with view   
1       Studio12 Monte Estoril, Cascais -Pool and tennis   
2                       Beguinhos: A balcony over Lisbon   
3                     Lisboa alojamento de curta duração   
4                     Room near the University of Lisbon   
...                                                  ...   
24199                           Urban Tram @ Lively Bica   
24200  New! Lisbon Designer's Hideaway Studio - Central!   
24201                                   Apartamento luxo   
24202                         Beach Studio 2- Hidden Gem   
24203                    Beautiful T1 + Terrace. Estrela   

                                             description  \
0      This fully renovated apartment located in the ...   
1      Nice studio at pool and garden level in a nice...   
2      A duplex apartment in Alfama, with a beautiful...   
3            To get to know Lisbon, close to everything.   
4                                         Not available.   
...                                                  ...   
24199  Cozy apartment located in the heart of the liv...   
24200  Step into comfort and convenience in this thou...   
24201  Bring the whole family to this fantastic place...   
24202  Cozy apartment 3 min from " Praia da Azarujinh...   
24203  Huge one bedroom apartment over 100sq m with a...   

                                   neighborhood_overview    host_id  \
0      The Alfama neighborhood is one of the oldest n...     753902   
1      Monte Estoril is a high standard area, close t...     758277   
2      The apartment is located on the edge of the ol...    1091599   
3              Close to Campo Grande garden, quiet area.    1108485   
4                                          Not available    1108485   
...                                                  ...        ...   
24199  The most photographed street in Lisbon is undo...   76223539   
24200                                      Not available    1320531   
24201                                      Not available  559577767   
24202                                      Not available  458564790   
24203                                      Not available    3249520   

        host_name host_response_time host_is_superhost  \
0           Bruno     within an hour                 f   
1       Margarida     within an hour                 f   
2       Francisco     within an hour                 t   
3           Maria       within a day                 t   
4           Maria       within a day                 t   
...           ...                ...               ...   
24199      BnBird     within an hour                 f   
24200      Rachel     within an hour                 f   
24201       Magda            Unknown                 f   
24202  Hidden Gem     within an hour                 f   
24203      Sylvie     within an hour                 f   

                   neighbourhood_cleansed  ... minimum_nights_avg_ntm  \
0                       Santa Maria Maior  ...                   3.00   
1                       Cascais e Estoril  ...                   3.00   
2                       Santa Maria Maior  ...                   3.00   
3                                Alvalade  ...                   2.44   
4                                Alvalade  ...                   2.44   
...                          

In [392]:
df.columns

Index(['id', 'source', 'name', 'description', 'neighborhood_overview',
       'host_id', 'host_name', 'host_response_time', 'host_is_superhost',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'amenities',
       'has_availability', 'first_review', 'last_review', 'instant_bookable',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'minimum_nights',
       'maximum_nights', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'host_response_rate',
       'host_acceptance_rate', 'price', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'review_scores_rating',
       'review_scores_accu

In [393]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24204 entries, 0 to 24203
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   id                                            24204 non-null  int64  
 1   source                                        24204 non-null  object 
 2   name                                          24204 non-null  object 
 3   description                                   24204 non-null  object 
 4   neighborhood_overview                         24204 non-null  object 
 5   host_id                                       24204 non-null  int64  
 6   host_name                                     24204 non-null  object 
 7   host_response_time                            24204 non-null  object 
 8   host_is_superhost                             24204 non-null  object 
 9   neighbourhood_cleansed                        24204 non-null 

**instant_bookable vs availability_30, host_acceptance_rate, price & beds**

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep=df[['availability_30','host_acceptance_rate','price','beds']] #De tipo numérico
Var_Dep=df['instant_bookable']

In [395]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [396]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)

In [397]:
#Se escalan todos los datos
escalar = StandardScaler()

In [398]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [399]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [400]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [401]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [402]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[ 792 2341]
 [ 509 3620]]


In [409]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision1 = precision_score(y_test, y_pred, average="binary", pos_label="t")
print("Precisión del modelo: ")
print(precision1)

Precisión del modelo: 
0.6072806576077839


In [410]:
from sklearn.metrics import precision_score

precision2 = precision_score(y_test, y_pred, average="binary", pos_label="f")
print("Precisión del modelo: ")
print(precision2)

Precisión del modelo: 
0.6087624903920061


In [423]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud1 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud1)

Exactitud del modelo: 
0.6075461305425502


In [412]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad1 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad1)

Sensibilidad del modelo: 
0.8767255994187455


In [413]:
from sklearn.metrics import recall_score

sensibilidad2 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad2)

Sensibilidad del modelo: 
0.25279285030322374


**source vs availability_30, price, latitude & longitude**

In [478]:
Vars_Indep=df[['availability_30','price','latitude','longitude']] #De tipo numérico
Var_Dep=df['source']

In [479]:
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)


In [482]:
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [483]:
y_pred = algoritmo.predict(X_test)
y_pred
#

array(['city scrape', 'city scrape', 'city scrape', ..., 'city scrape',
       'city scrape', 'city scrape'], dtype=object)

In [484]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[6371    5]
 [ 871   15]]


In [485]:
from sklearn.metrics import precision_score

precision3 = precision_score(y_test, y_pred, average="binary", pos_label="city scrape") 
print("Precisión del modelo: ")
print(precision3)

Precisión del modelo: 
0.879729356531345


In [486]:
from sklearn.metrics import precision_score

precision4 = precision_score(y_test, y_pred, average="binary", pos_label="previous scrape") 
print("Precisión del modelo: ")
print(precision4)

Precisión del modelo: 
0.75


In [487]:
from sklearn.metrics import accuracy_score

exactitud2 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud2)

Exactitud del modelo: 
0.8793720738088681


In [488]:
from sklearn.metrics import recall_score

sensibilidad3 = recall_score(y_test, y_pred, average="binary", pos_label="city scrape")
print("Sensibilidad del modelo: ")
print(sensibilidad3)

Sensibilidad del modelo: 
0.999215809284818


In [490]:
from sklearn.metrics import recall_score

sensibilidad4 = recall_score(y_test, y_pred, average="binary", pos_label="previous scrape")
print("Sensibilidad del modelo: ")
print(sensibilidad4)

Sensibilidad del modelo: 
0.016930022573363433


**host_is_superhost vs host_response_rate & review_scores_rating**

In [460]:
Vars_Indep=df[['host_response_rate','host_acceptance_rate','review_scores_rating']] #De tipo numérico
Var_Dep=df['host_is_superhost']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [461]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 't', 'f', 'f'], dtype=object)

In [463]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[4566  673]
 [1577  446]]


In [464]:
from sklearn.metrics import precision_score

precision5 = precision_score(y_test, y_pred, average="binary", pos_label="t") 
print("Precisión del modelo: ")
print(precision5)

Precisión del modelo: 
0.39857015192135836


In [465]:
precision6 = precision_score(y_test, y_pred, average="binary", pos_label="f") 
print("Precisión del modelo: ")
print(precision6)

Precisión del modelo: 
0.7432850398827934


In [466]:
exactitud3 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud3)

Exactitud del modelo: 
0.6901679977967502


In [467]:
sensibilidad5 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad5)

Sensibilidad del modelo: 
0.22046465645081562


In [469]:
sensibilidad6 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad6)

Sensibilidad del modelo: 
0.8715403702996755


**has_availability vs availability_30, price & availability_60**

In [491]:
Vars_Indep=df[['availability_30','price','availability_60']] #De tipo numérico
Var_Dep=df['has_availability']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [492]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [493]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[   0   20]
 [   0 7242]]


In [494]:
precision7 = precision_score(y_test, y_pred, average="binary", pos_label="t") 
print("Precisión del modelo: ")
print(precision7)

Precisión del modelo: 
0.9972459377581934


In [495]:
precision8 = precision_score(y_test, y_pred, average="binary", pos_label="f") 
print("Precisión del modelo: ")
print(precision8)

Precisión del modelo: 
0.0


c:\Users\lalob\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [496]:
exactitud4 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud4)

Exactitud del modelo: 
0.9972459377581934


In [497]:
sensibilidad7 = recall_score(y_test, y_pred, average="binary", pos_label="t")
print("Sensibilidad del modelo: ")
print(sensibilidad7)

Sensibilidad del modelo: 
1.0


In [498]:
sensibilidad8 = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo: ")
print(sensibilidad8)

Sensibilidad del modelo: 
0.0


**neighbourhood_group_cleansed vs latitude & longitude**

In [502]:
unico = np.unique(df["neighbourhood_group_cleansed"])
unico

array(['Lisboa', 'No Lisboa'], dtype=object)

In [501]:
df['neighbourhood_group_cleansed']= df['neighbourhood_group_cleansed'].replace(["Alenquer",'Amadora', 'Arruda Dos Vinhos', 'Azambuja', 'Cadaval',
       'Cascais', 'Loures', 'Lourinh', 'Mafra', 'Odivelas',
       'Oeiras', 'Sintra', 'Sobral De Monte Agrao', 'Torres Vedras',
       'Vila Franca De Xira'], "No Lisboa")
df["neighbourhood_group_cleansed"]

0           Lisboa
1        No Lisboa
2           Lisboa
3           Lisboa
4           Lisboa
           ...    
24199       Lisboa
24200       Lisboa
24201    No Lisboa
24202    No Lisboa
24203       Lisboa
Name: neighbourhood_group_cleansed, Length: 24204, dtype: object

In [503]:
Vars_Indep=df[['latitude', 'longitude']] #De tipo numérico
Var_Dep=df['neighbourhood_group_cleansed']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [504]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Lisboa', 'Lisboa', 'Lisboa', ..., 'No Lisboa', 'Lisboa', 'Lisboa'],
      dtype=object)

In [505]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[4905   47]
 [  88 2222]]


In [510]:
precision9 = precision_score(y_test, y_pred, average="binary", pos_label="Lisboa") 
print("Precisión del modelo: ")
print(precision9)

Precisión del modelo: 
0.9823753254556379


In [511]:
precision10 = precision_score(y_test, y_pred, average="binary", pos_label="No Lisboa") 
print("Precisión del modelo: ")
print(precision10)

Precisión del modelo: 
0.9792860290877038


In [512]:
exactitud5 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud5)

Exactitud del modelo: 
0.981410079867805


In [513]:
sensibilidad9 = recall_score(y_test, y_pred, average="binary", pos_label="Lisboa")
print("Sensibilidad del modelo: ")
print(sensibilidad9)

Sensibilidad del modelo: 
0.9905088852988692


In [514]:
sensibilidad10 = recall_score(y_test, y_pred, average="binary", pos_label="No Lisboa")
print("Sensibilidad del modelo: ")
print(sensibilidad10)

Sensibilidad del modelo: 
0.9619047619047619


**room_type vs accommodates, bathrooms, bedrooms & beds**

In [560]:
unico = np.unique(df["room_type"])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [561]:
df['room_type']= df['room_type'].replace(['Hotel room','Private room', 'Shared room'], "No Entire home")
df["room_type"]

0        Entire home/apt
1        Entire home/apt
2        Entire home/apt
3         No Entire home
4         No Entire home
              ...       
24199    Entire home/apt
24200    Entire home/apt
24201    Entire home/apt
24202    Entire home/apt
24203    Entire home/apt
Name: room_type, Length: 24204, dtype: object

In [562]:
Vars_Indep=df[['accommodates','bathrooms','bedrooms','beds']] #De tipo numérico
Var_Dep=df['room_type']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [563]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Entire home/apt', 'Entire home/apt', 'Entire home/apt', ...,
       'Entire home/apt', 'No Entire home', 'No Entire home'],
      dtype=object)

In [564]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[5027  301]
 [ 946  988]]


In [565]:
precision11 = precision_score(y_test, y_pred, average="binary", pos_label="Entire home/apt") 
print("Precisión del modelo: ")
print(precision11)

Precisión del modelo: 
0.8416206261510129


In [566]:
precision12 = precision_score(y_test, y_pred, average="binary", pos_label="No Entire home") 
print("Precisión del modelo: ")
print(precision12)

Precisión del modelo: 
0.7664856477889838


In [567]:
exactitud6 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud6)

Exactitud del modelo: 
0.8282842192233545


In [568]:
sensibilidad11 = recall_score(y_test, y_pred, average="binary", pos_label="Entire home/apt")
print("Sensibilidad del modelo: ")
print(sensibilidad11)

Sensibilidad del modelo: 
0.943506006006006


In [569]:
sensibilidad12 = recall_score(y_test, y_pred, average="binary", pos_label="No Entire home")
print("Sensibilidad del modelo: ")
print(sensibilidad12)

Sensibilidad del modelo: 
0.5108583247156153


**accommodates vs price, bathrooms, bedrooms & beds**

In [532]:
df['accommodates']

0        4.0
1        3.0
2        2.0
3        1.0
4        1.0
        ... 
24199    3.0
24200    2.0
24201    6.0
24202    6.0
24203    3.0
Name: accommodates, Length: 24204, dtype: float64

In [533]:
Min = df['accommodates'].min()
Max = df['accommodates'].max()

intervalos = [Min - 1, 3, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["3 o menos", "Más de 3"]

df['accommodates'] = pd.cut(df['accommodates'], bins=intervalos, labels=categorias, right=True)
df['accommodates']

0         Más de 3
1        3 o menos
2        3 o menos
3        3 o menos
4        3 o menos
           ...    
24199    3 o menos
24200    3 o menos
24201     Más de 3
24202     Más de 3
24203    3 o menos
Name: accommodates, Length: 24204, dtype: category
Categories (2, object): ['3 o menos' < 'Más de 3']

In [534]:
df['accommodates'].isnull().sum()

0

In [535]:
Vars_Indep=df[['price','bathrooms','bedrooms','beds']] #De tipo numérico
Var_Dep=df['accommodates']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [536]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['3 o menos', '3 o menos', 'Más de 3', ..., '3 o menos', 'Más de 3',
       '3 o menos'], dtype=object)

In [537]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3121  448]
 [ 826 2867]]


In [539]:
precision13 = precision_score(y_test, y_pred, average="binary", pos_label="Más de 3") 
print("Precisión del modelo: ")
print(precision13)

Precisión del modelo: 
0.8648567119155355


In [540]:
precision14 = precision_score(y_test, y_pred, average="binary", pos_label="3 o menos") 
print("Precisión del modelo: ")
print(precision14)

Precisión del modelo: 
0.7907271345325564


In [542]:
exactitud7 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud7)

Exactitud del modelo: 
0.8245662351969154


In [543]:
sensibilidad13 = recall_score(y_test, y_pred, average="binary", pos_label="Más de 3")
print("Sensibilidad del modelo: ")
print(sensibilidad13)

Sensibilidad del modelo: 
0.7763336041158949


In [544]:
sensibilidad14 = recall_score(y_test, y_pred, average="binary", pos_label="3 o menos")
print("Sensibilidad del modelo: ")
print(sensibilidad14)

Sensibilidad del modelo: 
0.8744746427570748


**reviews_per_month vs number_of_reviews, number_of_reviews_ltm & number_of_reviews_l30d**

In [571]:
df['reviews_per_month']

0        0.92
1        0.43
2        2.01
3        0.36
4        0.42
         ... 
24199    0.00
24200    0.00
24201    0.00
24202    0.00
24203    0.00
Name: reviews_per_month, Length: 24204, dtype: float64

In [572]:
Min = df['reviews_per_month'].min()
Max = df['reviews_per_month'].max()

intervalos = [Min - 1, 1, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["1 o menos", "Más de 1"]

df['reviews_per_month'] = pd.cut(df['reviews_per_month'], bins=intervalos, labels=categorias, right=True)
df['reviews_per_month']

0        1 o menos
1        1 o menos
2         Más de 1
3        1 o menos
4        1 o menos
           ...    
24199    1 o menos
24200    1 o menos
24201    1 o menos
24202    1 o menos
24203    1 o menos
Name: reviews_per_month, Length: 24204, dtype: category
Categories (2, object): ['1 o menos' < 'Más de 1']

In [ ]:
Vars_Indep=df[['number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d']]
Var_Dep=df['reviews_per_month']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [581]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['1 o menos', '1 o menos', 'Más de 1', ..., '1 o menos',
       '1 o menos', 'Más de 1'], dtype=object)

In [582]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[3614  370]
 [ 596 2682]]


In [583]:
precision15 = precision_score(y_test, y_pred, average="binary", pos_label="Más de 1") 
print("Precisión del modelo: ")
print(precision15)

Precisión del modelo: 
0.8787680209698558


In [584]:
precision16 = precision_score(y_test, y_pred, average="binary", pos_label="1 o menos") 
print("Precisión del modelo: ")
print(precision16)

Precisión del modelo: 
0.8584323040380047


In [579]:
exactitud8 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud8)

Exactitud del modelo: 
0.49283943817130266


In [585]:
sensibilidad15 = recall_score(y_test, y_pred, average="binary", pos_label="Más de 1")
print("Sensibilidad del modelo: ")
print(sensibilidad15)

Sensibilidad del modelo: 
0.8181818181818182


In [586]:
sensibilidad16 = recall_score(y_test, y_pred, average="binary", pos_label="1 o menos")
print("Sensibilidad del modelo: ")
print(sensibilidad16)

Sensibilidad del modelo: 
0.9071285140562249


**review_scores_rating vs review_scores_cleanliness, review_scores_accuracy, review_scores_checkin, review_scores_communication, review_scores_location & review_scores_value**

In [588]:
df['review_scores_rating']

0        4.68
1        4.45
2        4.83
3        4.88
4        5.00
         ... 
24199    4.69
24200    4.69
24201    4.69
24202    4.69
24203    4.69
Name: review_scores_rating, Length: 24204, dtype: float64

In [589]:
Min = df['review_scores_rating'].min()
Max = df['review_scores_rating'].max()

intervalos = [Min - 1, 4.8, Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["Menos de 4.8", "4.8 o más"]

df['review_scores_rating'] = pd.cut(df['review_scores_rating'], bins=intervalos, labels=categorias, right=True)
df['review_scores_rating']

0        Menos de 4.8
1        Menos de 4.8
2           4.8 o más
3           4.8 o más
4           4.8 o más
             ...     
24199    Menos de 4.8
24200    Menos de 4.8
24201    Menos de 4.8
24202    Menos de 4.8
24203    Menos de 4.8
Name: review_scores_rating, Length: 24204, dtype: category
Categories (2, object): ['Menos de 4.8' < '4.8 o más']

In [590]:
Vars_Indep=df[['review_scores_cleanliness','review_scores_accuracy','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value']]
Var_Dep=df['review_scores_rating']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [591]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Menos de 4.8', 'Menos de 4.8', '4.8 o más', ..., '4.8 o más',
       'Menos de 4.8', 'Menos de 4.8'], dtype=object)

In [592]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[2207  360]
 [ 333 4362]]


In [593]:
precision17 = precision_score(y_test, y_pred, average="binary", pos_label="4.8 o más") 
print("Precisión del modelo: ")
print(precision17)

Precisión del modelo: 
0.8688976377952756


In [594]:
precision18 = precision_score(y_test, y_pred, average="binary", pos_label="Menos de 4.8") 
print("Precisión del modelo: ")
print(precision18)

Precisión del modelo: 
0.9237611181702668


In [595]:
exactitud9 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud9)

Exactitud del modelo: 
0.9045717433213991


In [596]:
sensibilidad17 = recall_score(y_test, y_pred, average="binary", pos_label="4.8 o más")
print("Sensibilidad del modelo: ")
print(sensibilidad17)

Sensibilidad del modelo: 
0.859758472925594


In [597]:
sensibilidad18 = recall_score(y_test, y_pred, average="binary", pos_label="Menos de 4.8")
print("Sensibilidad del modelo: ")
print(sensibilidad18)

Sensibilidad del modelo: 
0.929073482428115


**price vs accommodates, bathrooms, bedrooms & beds**

In [668]:
df = pd.read_csv('Lisboa por IQR2.csv')
df =df.drop(labels=["Unnamed: 0"], axis=1)
df

id           source  \
0                   208683      city scrape   
1                   211614  previous scrape   
2                   211616      city scrape   
3                   214729      city scrape   
4                   217281      city scrape   
...                    ...              ...   
24199  1243403799584587485      city scrape   
24200  1243421531996967673      city scrape   
24201  1243488183394801906      city scrape   
24202  1243509538559076353      city scrape   
24203  1243552535635447045      city scrape   

                                                    name  \
0                       Cozy central apartment with view   
1       Studio12 Monte Estoril, Cascais -Pool and tennis   
2                       Beguinhos: A balcony over Lisbon   
3                     Lisboa alojamento de curta duração   
4                     Room near the University of Lisbon   
...                                                  ...   
24199                           Urban Tram @ Lively Bica   
24200  New! Lisbon Designer's Hideaway Studio - Central!   
24201                                   Apartamento luxo   
24202                         Beach Studio 2- Hidden Gem   
24203                    Beautiful T1 + Terrace. Estrela   

                                             description  \
0      This fully renovated apartment located in the ...   
1      Nice studio at pool and garden level in a nice...   
2      A duplex apartment in Alfama, with a beautiful...   
3            To get to know Lisbon, close to everything.   
4                                         Not available.   
...                                                  ...   
24199  Cozy apartment located in the heart of the liv...   
24200  Step into comfort and convenience in this thou...   
24201  Bring the whole family to this fantastic place...   
24202  Cozy apartment 3 min from " Praia da Azarujinh...   
24203  Huge one bedroom apartment over 100sq m with a...   

                                   neighborhood_overview    host_id  \
0      The Alfama neighborhood is one of the oldest n...     753902   
1      Monte Estoril is a high standard area, close t...     758277   
2      The apartment is located on the edge of the ol...    1091599   
3              Close to Campo Grande garden, quiet area.    1108485   
4                                          Not available    1108485   
...                                                  ...        ...   
24199  The most photographed street in Lisbon is undo...   76223539   
24200                                      Not available    1320531   
24201                                      Not available  559577767   
24202                                      Not available  458564790   
24203                                      Not available    3249520   

        host_name host_response_time host_is_superhost  \
0           Bruno     within an hour                 f   
1       Margarida     within an hour                 f   
2       Francisco     within an hour                 t   
3           Maria       within a day                 t   
4           Maria       within a day                 t   
...           ...                ...               ...   
24199      BnBird     within an hour                 f   
24200      Rachel     within an hour                 f   
24201       Magda            Unknown                 f   
24202  Hidden Gem     within an hour                 f   
24203      Sylvie     within an hour                 f   

                   neighbourhood_cleansed  ... minimum_nights_avg_ntm  \
0                       Santa Maria Maior  ...                   3.00   
1                       Cascais e Estoril  ...                   3.00   
2                       Santa Maria Maior  ...                   3.00   
3                                Alvalade  ...                   2.44   
4                                Alvalade  ...                   2.44   
...                          

In [667]:
df['price']

0        2.727273
1        2.727273
2        3.590909
3        1.363636
4        1.000000
           ...   
24199    2.727273
24200    4.727273
24201    6.181818
24202    7.909091
24203    4.954545
Name: price, Length: 24204, dtype: float64

In [651]:
promedio_price = df['price'].mean()
print(promedio_price)

49.687537082619286


In [669]:
Min = df['price'].min()
Max = df['price'].max()

intervalos = [Min - 1,100 , Max]  # Min - 1 para asegurar incluir valores mínimos
categorias = ["Menos de 100", "100 o más"]

df['price'] = pd.cut(df['price'], bins=intervalos, labels=categorias, right=True)
df['price']

0        Menos de 100
1        Menos de 100
2        Menos de 100
3        Menos de 100
4        Menos de 100
             ...     
24199    Menos de 100
24200       100 o más
24201       100 o más
24202       100 o más
24203       100 o más
Name: price, Length: 24204, dtype: category
Categories (2, object): ['Menos de 100' < '100 o más']

In [670]:
Vars_Indep=df[['accommodates','bathrooms','bedrooms','beds']]
Var_Dep=df['price']
X= Vars_Indep
y= Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=None)
escalar = StandardScaler()
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [671]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['100 o más', 'Menos de 100', 'Menos de 100', ..., '100 o más',
       'Menos de 100', '100 o más'], dtype=object)

In [672]:
matriz = confusion_matrix(y_test, y_pred)
print ('Matriz de Confusión: ')
print(matriz)

Matriz de Confusión: 
[[2991 1198]
 [ 972 2101]]


In [673]:
precision19 = precision_score(y_test, y_pred, average="binary", pos_label="100 o más") 
print("Precisión del modelo: ")
print(precision19)

Precisión del modelo: 
0.7547312641937926


In [674]:
precision20 = precision_score(y_test, y_pred, average="binary", pos_label="Menos de 100") 
print("Precisión del modelo: ")
print(precision20)

Precisión del modelo: 
0.6368596544407397


In [675]:
exactitud10 = accuracy_score(y_test,y_pred)
print("Exactitud del modelo: ")
print(exactitud10)

Exactitud del modelo: 
0.7011842467639768


In [676]:
sensibilidad19 = recall_score(y_test, y_pred, average="binary", pos_label="100 o más")
print("Sensibilidad del modelo: ")
print(sensibilidad19)

Sensibilidad del modelo: 
0.7140128909047505


In [677]:
sensibilidad20 = recall_score(y_test, y_pred, average="binary", pos_label="Menos de 100")
print("Sensibilidad del modelo: ")
print(sensibilidad20)

Sensibilidad del modelo: 
0.6836967133094696


In [ ]:
print("Tabla de estadísticos de regresión logística")
print("1 hace referencia a valores true o categorías con valores mayores, 2 a valores false o categorías con valores menores.")
resultados = {
    'Métrica': ['Precisión T o >','Precisión F o <', 'Sensibilidad T o >','Sensibilidad F o >','Exactitud'],
    'instant_bookable': [precision1,precision2,sensibilidad1,sensibilidad2,exactitud1],
    'source': [precision3,precision4,sensibilidad3,sensibilidad4,exactitud2], #city scrape es true, previous scrape es false
    'host_is_superhost': [precision5,precision6,sensibilidad5,sensibilidad6,exactitud3],
    'has_availability': [precision7,precision8,sensibilidad7,sensibilidad8,exactitud4],
    'neighbourhood_group_cleansed': [precision9,precision10,sensibilidad9,sensibilidad10,exactitud5], #Lisboa es true y No Lisboa es false
    'room_type': [precision11,precision12,sensibilidad11,sensibilidad12,exactitud6], #Entire home/apt es true, #No Entire home es false
    'accommodates': [precision13,precision14,sensibilidad13,sensibilidad14,exactitud7], #Más de 3 es true, 3 o menos es false
    'reviews_per_month': [precision15,precision16,sensibilidad15,sensibilidad16,exactitud8], #Más de 1 es true, 1 o menos es false
    'review_scores_rating': [precision17,precision18,sensibilidad17,sensibilidad18,exactitud9], #4.8 o más es true, menos de 4.8 es false
    'price': [precision19,precision20,sensibilidad19,sensibilidad20,exactitud10] #100 o más es true, menos de 100 es false
}

# Convertirlo en DataFrame
df_resultados = pd.DataFrame(resultados)

# Mostrar la tabla
df_resultados


Tabla de estadísticos de regresión logística
1 hace referencia a valores true o categorías con valores mayores, 2 a valores false o categorías con valores menores.


Métrica  instant_bookable    source  host_is_superhost  \
0     Precisión T o >          0.607281  0.879729           0.398570   
1     Precisión F o <          0.608762  0.750000           0.743285   
2  Sensibilidad T o >          0.876726  0.999216           0.220465   
3  Sensibilidad F o >          0.252793  0.016930           0.871540   
4           Exactitud          0.607546  0.879372           0.690168   

   has_availability  neighbourhood_group_cleansed  room_type  accommodates  \
0          0.997246                      0.982375   0.841621      0.864857   
1          0.000000                      0.979286   0.766486      0.790727   
2          1.000000                      0.990509   0.943506      0.776334   
3          0.000000                      0.961905   0.510858      0.874475   
4          0.997246                      0.981410   0.828284      0.824566   

   reviews_per_month  review_scores_rating     price  
0           0.878768              0.868898  0.754731  
1           0.858432              0.923761  0.636860  
2           0.818182              0.859758  0.714013  
3           0.907129              0.929073  0.683697  
4           0.492839              0.904572  0.701184